### ISSUE TITLE
Upstream is no set when a new branch is created

### ISSUE THREAD

**Issue by srf-stefan** [claudio-walser/gitcd#22]
root@asdf [feature/asdf-xxxx-ftp-accounts]$ git push
fatal: The current branch feature/asdf-xxx-ftp-accounts has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin feature/asdf-xxx-ftp-accounts

**Comment by claudio-walser** [comment]
thanks, i am going to implement that.
BTW: the --set-upstream option is deprecated. You should use --track or --set-upstream-to instead

**Comment by claudio-walser** [comment]
fixed with https://github.com/claudio-walser/gitcd/pull/23
